### ISSUE TITLE
Route property must be named `url`

### ISSUE THREAD

**Issue by Prokyonn** [sulu/SuluContentBundle#261]
Currently the SuluContentBundle forces the user to have the route property named `url` in the template. 

This behaviour is not consistent throughout Sulu. The ArticleBundle did not force you to have to property named `url` usually it was called `routePath`.

Therefore migrating the ArticleBundle to the ContentBundle requires also a migration of the XML templates.

#### Possible solution

* Add the required steps to the UPGRADE.md.
* Add a MetadataListener that shows an error in the UI when an entity detail page is opened with a `route` property that is not named `url`.
* Force a `url` property in the template structure e.g.:
```
sulu_core:
    content:
        structure:
            required_properties:
                home:
                    - title
                    - url
```
